import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import HomeLayout from "./components/layout/homeLayout";
import ProvidersComponent from "./components/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cocoTala",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersComponent>
          <HomeLayout>{children}</HomeLayout>
        </ProvidersComponent>
      </body>
    </html>
  );
}
